apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: image-name
      type: string
      default: "us.icr.io/tax-calculator/app:latest"
    - name: application-name
      type: string
      default: "tax-calculator-app"
  tasks:
    - name: install-dependencies
      taskRef:
        name: npm-install
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: test
      runAfter: [install-dependencies]
      taskRef:
        name: jasmine-test
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build
      runAfter: [test]
      taskRef:
        name: build-and-push
      params:
        - name: image
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: deploy
      runAfter: [build]
      taskRef:
        name: deploy-to-cloud
      params:
        - name: image
          value: $(params.image-name)
        - name: app-name
          value: $(params.application-name)
      workspaces:
        - name: source
          workspace: pipeline-workspace
